# Generated by Django 2.0 on 2019-06-01 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sys_set', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dep_id', models.AutoField(help_text='部门id', primary_key=True, serialize=False, verbose_name='部门编号')),
                ('dep_name', models.CharField(help_text='部门名称', max_length=10, verbose_name='部门名称')),
                ('org_id', models.ForeignKey(help_text='归属组织', on_delete=django.db.models.deletion.DO_NOTHING, to='sys_set.Organization', verbose_name='归属组织')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
