# Generated by Django 2.0 on 2019-05-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(help_text='部门id', primary_key=True, serialize=False, verbose_name='部门编号')),
                ('dep_name', models.CharField(help_text='部门名称', max_length=10, verbose_name='部门名称')),
            ],
        ),
    ]
