# Generated by Django 2.0 on 2019-06-01 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_tel',
            field=models.CharField(help_text='电话', max_length=15, null=True, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='department',
            name='dep_type',
            field=models.IntegerField(choices=[(0, '分公司'), (1, '校区'), (2, '部门')], null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='superior_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.Department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='org_id',
            field=models.ForeignKey(help_text='公司id', on_delete=django.db.models.deletion.DO_NOTHING, to='sys_set.Organization', verbose_name='公司名称'),
        ),
    ]
