# Generated by Django 2.0.5 on 2019-06-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20190601_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_type',
            field=models.IntegerField(choices=[(0, '分公司'), (1, '校区'), (2, '部门')], null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='department',
            name='superior_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.Department', verbose_name='上级部门'),
        ),
    ]
