# Generated by Django 2.0 on 2019-05-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='渠道名称', max_length=10, verbose_name='渠道名称')),
                ('del_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'channel',
            },
        ),
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='渠道分类名称', max_length=10, verbose_name='渠道分类')),
                ('del_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'channel_type',
            },
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('tel', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(0, '女'), (1, '男'), (3, '未知')])),
                ('add', models.CharField(help_text='年龄', max_length=40)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clue.Channel')),
            ],
            options={
                'db_table': 'clue',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_superior',
            field=models.ForeignKey(help_text='渠道分类id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clue.ChannelType', verbose_name='渠道分类'),
        ),
    ]
