# Generated by Django 2.0.5 on 2019-06-02 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('cha_name', models.CharField(help_text='渠道名称', max_length=10, unique=True, verbose_name='渠道名称')),
                ('del_flag', models.BooleanField(default=False, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '渠道',
                'verbose_name_plural': '渠道管理',
            },
        ),
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('channel_type_id', models.AutoField(help_text='渠道分类id', primary_key=True, serialize=False, verbose_name='渠道分类编号')),
                ('cha_type_name', models.CharField(help_text='渠道分类名称', max_length=10, unique=True, verbose_name='渠道分类名称')),
                ('del_flag', models.BooleanField(default=False, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '渠道类型',
                'verbose_name_plural': '渠道类型管理',
            },
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('clue_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='姓名', max_length=10, verbose_name='姓名')),
                ('tel', models.CharField(help_text='电话', max_length=15, verbose_name='电话')),
                ('age', models.IntegerField(blank=True, help_text='年龄', null=True, verbose_name='年龄')),
                ('sex', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], help_text='性别,0:女,1:男,未知留空', null=True, verbose_name='性别')),
                ('add', models.CharField(blank=True, help_text='地址', max_length=40, null=True, verbose_name='地址')),
                ('channel_id', models.ForeignKey(help_text='来源渠道', on_delete=django.db.models.deletion.DO_NOTHING, to='clue.Channel', verbose_name='来源渠道')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='channel_user_type_create', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('delete_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='channel_user_type_delete', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='channel_user_type_update', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type_id',
            field=models.ForeignKey(help_text='渠道分类id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clue.ChannelType', verbose_name='渠道分类'),
        ),
    ]
