# Generated by Django 2.0 on 2019-05-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='channeltype',
            table=None,
        ),
    ]
