# Generated by Django 2.0 on 2019-06-01 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='channel_user_type_create', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='clue',
            name='delete_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='channel_user_type_delete', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='clue',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='channel_user_type_update', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type_id',
            field=models.ForeignKey(help_text='渠道分类id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clue.ChannelType', verbose_name='渠道分类'),
        ),
    ]
