# Generated by Django 2.0 on 2019-07-05 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eduadmin', '0001_initial'),
        ('clue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='clue',
            name='follow_up_people',
            field=models.ForeignKey(blank=True, help_text='跟进人', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_follow_up_people', to=settings.AUTH_USER_MODEL, verbose_name='跟进人'),
        ),
        migrations.AddField(
            model_name='clue',
            name='intended_course',
            field=models.ForeignKey(blank=True, help_text='意向课程', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_intended_course', to='eduadmin.Course', verbose_name='意向课程'),
        ),
        migrations.AddField(
            model_name='clue',
            name='intended_school',
            field=models.ForeignKey(blank=True, help_text='意向校区', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_intended_school', to='sys.Department', verbose_name='意向校区'),
        ),
        migrations.AddField(
            model_name='clue',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='clue',
            name='plan_course',
            field=models.ForeignKey(blank=True, help_text='安排课程', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_plan_course', to='eduadmin.Course', verbose_name='安排课程'),
        ),
        migrations.AddField(
            model_name='clue',
            name='plan_reception',
            field=models.ForeignKey(blank=True, help_text='安排接待', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_plan_reception', to=settings.AUTH_USER_MODEL, verbose_name='安排接待'),
        ),
        migrations.AddField(
            model_name='clue',
            name='plan_school',
            field=models.ForeignKey(blank=True, help_text='安排校区', null=True, on_delete=True, related_name='clue_plan_school', to='sys.Department', verbose_name='安排校区'),
        ),
        migrations.AddField(
            model_name='clue',
            name='plan_teacher',
            field=models.ForeignKey(blank=True, help_text='安排校区', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_plan_teacher', to='eduadmin.Teacher', verbose_name='安排老师'),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.ForeignKey(help_text='渠道分类id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clue.ChannelType', verbose_name='渠道分类'),
        ),
    ]
