# Generated by Django 2.0 on 2019-07-23 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eduadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sys', '0001_initial'),
        ('clue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='visit',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='visit',
            name='ordered_course',
            field=models.ForeignKey(blank=True, help_text='安排课程', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue_plan_course', to='eduadmin.Course', verbose_name='安排课程'),
        ),
        migrations.AddField(
            model_name='visit',
            name='ordered_reception',
            field=models.ForeignKey(help_text='安排接待', on_delete=django.db.models.deletion.CASCADE, related_name='clue_plan_reception', to=settings.AUTH_USER_MODEL, verbose_name='安排接待'),
        ),
        migrations.AddField(
            model_name='visit',
            name='ordered_teacher',
            field=models.ForeignKey(blank=True, help_text='安排校区', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue_plan_teacher', to='eduadmin.Teacher', verbose_name='安排老师'),
        ),
        migrations.AddField(
            model_name='visit',
            name='school',
            field=models.ForeignKey(help_text='安排校区', on_delete=True, related_name='clue_plan_school', to='sys.Department', verbose_name='安排校区'),
        ),
        migrations.AddField(
            model_name='followrecord',
            name='clue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clue.Clue', verbose_name='关联线索'),
        ),
        migrations.AddField(
            model_name='followrecord',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='followrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='clue',
            name='channel',
            field=models.ForeignKey(help_text='来源渠道', on_delete=django.db.models.deletion.DO_NOTHING, to='clue.Channel', verbose_name='来源渠道'),
        ),
        migrations.AddField(
            model_name='clue',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='clue',
            name='failing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clue.FailingType', verbose_name='未成交原因类型'),
        ),
        migrations.AddField(
            model_name='clue',
            name='follow_up_person',
            field=models.ForeignKey(blank=True, help_text='跟进人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue_follow_up_people', to=settings.AUTH_USER_MODEL, verbose_name='跟进人'),
        ),
        migrations.AddField(
            model_name='clue',
            name='intended_course',
            field=models.ManyToManyField(blank=True, help_text='意向课程', related_name='clue_intended_course', to='eduadmin.Course', verbose_name='意向课程'),
        ),
        migrations.AddField(
            model_name='clue',
            name='intended_school',
            field=models.ManyToManyField(blank=True, help_text='意向校区', related_name='clue_intended_school', to='sys.Department', verbose_name='意向校区'),
        ),
        migrations.AddField(
            model_name='clue',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='channeltype',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ChannelType_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='channeltype',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ChannelType_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='channel',
            name='type',
            field=models.ForeignKey(help_text='渠道分类id', on_delete=django.db.models.deletion.CASCADE, to='clue.ChannelType', verbose_name='渠道分类'),
        ),
    ]
