# Generated by Django 2.0 on 2019-07-06 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clue', '0002_auto_20190705_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='follow_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='跟进人'),
            preserve_default=False,
        ),
    ]
