# Generated by Django 2.0.5 on 2019-06-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0002_auto_20190601_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': '渠道', 'verbose_name_plural': '渠道管理'},
        ),
        migrations.AlterModelOptions(
            name='channeltype',
            options={'verbose_name': '渠道类型', 'verbose_name_plural': '渠道类型管理'},
        ),
    ]
