# Generated by Django 2.0 on 2019-07-06 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clue', '0003_clue_follow_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='follow_person',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='follow_up_people',
        ),
        migrations.AddField(
            model_name='clue',
            name='follow_up_person',
            field=models.ForeignKey(blank=True, help_text='跟进人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue_follow_up_people', to=settings.AUTH_USER_MODEL, verbose_name='跟进人'),
        ),
    ]
