# Generated by Django 2.0 on 2019-06-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0003_auto_20190603_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='channeltype',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='creator',
        ),
    ]
