# Generated by Django 2.0.5 on 2019-06-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0003_auto_20190601_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='del_flag',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='channeltype',
            name='del_flag',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
    ]
