# Generated by Django 2.0 on 2019-07-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0020_auto_20190729_1615'),
        ('clue', '0003_auto_20190727_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channeltype',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clue',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='failingtype',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followrecord',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
    ]
