# Generated by Django 2.0 on 2019-06-03 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clue', '0004_auto_20190603_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clue',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
