# Generated by Django 2.0 on 2019-07-07 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0004_auto_20190706_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='input_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='录入日期', verbose_name='录入日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clue',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], help_text="((0, '女'), (1, '男'))", null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '下次联系'), (1, '成功约访'), (2, '已到访'), (3, '无法成交'), (4, '已报名')], help_text="线索状态((0, '下次联系'), (1, '成功约访'), (2, '已到访'), (3, '无法成交'), (4, '已报名'))", null=True, verbose_name='线索状态'),
        ),
    ]
