# Generated by Django 2.0 on 2019-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0002_resource_resource_key'),
        ('eduadmin', '0002_auto_20190705_1116'),
        ('clue', '0005_auto_20190707_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['channel_id'], 'verbose_name': '渠道', 'verbose_name_plural': '渠道管理'},
        ),
        migrations.RemoveField(
            model_name='clue',
            name='intended_course',
        ),
        migrations.AddField(
            model_name='clue',
            name='intended_course',
            field=models.ManyToManyField(blank=True, help_text='意向课程', related_name='clue_intended_course', to='eduadmin.Course', verbose_name='意向课程'),
        ),
        migrations.RemoveField(
            model_name='clue',
            name='intended_school',
        ),
        migrations.AddField(
            model_name='clue',
            name='intended_school',
            field=models.ManyToManyField(blank=True, help_text='意向校区', related_name='clue_intended_school', to='sys.Department', verbose_name='意向校区'),
        ),
    ]
