# Generated by Django 2.0 on 2019-07-08 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduadmin', '0002_auto_20190705_1116'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sys', '0002_resource_resource_key'),
        ('clue', '0006_auto_20190708_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('del_flag', models.BooleanField(default=False, help_text='已删除', verbose_name='已删除')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=150, null=True, verbose_name='备注')),
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_status', models.IntegerField(blank=True, choices=[(0, '约访'), (1, '试听')], help_text="((0, '约访'), (1, '试听'))", null=True, verbose_name='访问状态')),
                ('visit_date', models.DateField(blank=True, help_text='安排日期', null=True, verbose_name='安排日期')),
                ('visit_time', models.TimeField(blank=True, help_text='安排时间', null=True, verbose_name='安排时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='clue',
            name='auxiliary_status',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='plan_course',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='plan_date',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='plan_reception',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='plan_school',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='plan_teacher',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='plan_time',
        ),
        migrations.AddField(
            model_name='visit',
            name='clue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clue.Clue', verbose_name='线索'),
        ),
        migrations.AddField(
            model_name='visit',
            name='ordered_course',
            field=models.ForeignKey(blank=True, help_text='安排课程', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue_plan_course', to='eduadmin.Course', verbose_name='安排课程'),
        ),
        migrations.AddField(
            model_name='visit',
            name='ordered_reception',
            field=models.ForeignKey(blank=True, help_text='安排接待', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue_plan_reception', to=settings.AUTH_USER_MODEL, verbose_name='安排接待'),
        ),
        migrations.AddField(
            model_name='visit',
            name='ordered_teacher',
            field=models.ForeignKey(blank=True, help_text='安排校区', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clue_plan_teacher', to='eduadmin.Teacher', verbose_name='安排老师'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_school',
            field=models.ForeignKey(blank=True, help_text='安排校区', null=True, on_delete=True, related_name='clue_plan_school', to='sys.Department', verbose_name='安排校区'),
        ),
    ]
