# Generated by Django 2.0 on 2019-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0006_auto_20190730_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='status',
            field=models.IntegerField(choices=[(4, '无法成交'), (5, '已报名')], default=0, help_text="线索状态((4, '无法成交'), (5, '已报名'))", verbose_name='线索状态'),
        ),
    ]
