# Generated by Django 2.0 on 2019-08-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0007_auto_20190730_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_data',
            field=models.DateField(default='2018-11-11', help_text='安排日期', verbose_name='安排日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.TimeField(help_text='安排时间', verbose_name='安排时间'),
        ),
    ]
