# Generated by Django 2.0 on 2019-06-04 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0006_auto_20190604_0906'),
        ('sys_set', '0005_auto_20190603_2011'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clue', '0007_auto_20190603_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='auxiliary_status',
            field=models.IntegerField(blank=True, choices=[(0, '约访'), (1, '试听')], help_text="((0, '约访'), (1, '试听'))", null=True, verbose_name='辅助状态'),
        ),
        migrations.AddField(
            model_name='clue',
            name='plan_course',
            field=models.ForeignKey(blank=True, help_text='安排课程', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_plan_course', to='edu_admin.Course', verbose_name='安排课程'),
        ),
        migrations.AddField(
            model_name='clue',
            name='plan_date',
            field=models.DateField(blank=True, help_text='安排日期', null=True, verbose_name='安排日期'),
        ),
        migrations.AddField(
            model_name='clue',
            name='plan_reception',
            field=models.ForeignKey(blank=True, help_text='安排接待', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_plan_reception', to=settings.AUTH_USER_MODEL, verbose_name='安排接待'),
        ),
        migrations.AddField(
            model_name='clue',
            name='plan_school',
            field=models.ForeignKey(blank=True, help_text='安排校区', null=True, on_delete=True, related_name='clue_plan_school', to='sys_set.Department', verbose_name='安排校区'),
        ),
        migrations.AddField(
            model_name='clue',
            name='plan_teacher',
            field=models.ForeignKey(blank=True, help_text='安排校区', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_plan_teacher', to='edu_admin.Teacher', verbose_name='安排老师'),
        ),
        migrations.AddField(
            model_name='clue',
            name='plan_time',
            field=models.TimeField(blank=True, help_text='安排日期', null=True, verbose_name='安排日期'),
        ),
        migrations.AddField(
            model_name='clue',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '下次联系'), (1, '成功约访'), (2, '已到访'), (3, '无法成交'), (4, '已报名')], help_text='线索状态', null=True, verbose_name='线索状态'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='follow_up_people',
            field=models.ForeignKey(blank=True, help_text='跟进人', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_follow_up_people', to=settings.AUTH_USER_MODEL, verbose_name='跟进人'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='intended_course',
            field=models.ForeignKey(blank=True, help_text='意向课程', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_intended_course', to='edu_admin.Course', verbose_name='意向课程'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='intended_school',
            field=models.ForeignKey(blank=True, help_text='意向校区', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_intended_school', to='sys_set.Department', verbose_name='意向校区'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clue_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], help_text="((0, '下次联系'), (1, '成功约访'), (2, '已到访'), (3, '无法成交'), (4, '已报名'))", null=True, verbose_name='性别'),
        ),
    ]
