# Generated by Django 2.0 on 2019-07-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0008_auto_20190709_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_status',
        ),
        migrations.AddField(
            model_name='visit',
            name='is_visit',
            field=models.BooleanField(default=1, verbose_name='访问状态'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.IntegerField(choices=[(0, '约访'), (1, '试听')], default=1, help_text="访问类型((0, '约访'), (1, '试听'))", verbose_name='访问类型'),
            preserve_default=False,
        ),
    ]
