# Generated by Django 2.0 on 2019-06-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0008_auto_20190604_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='plan_time',
            field=models.TimeField(blank=True, help_text='安排时间', null=True, verbose_name='安排时间'),
        ),
    ]
