# Generated by Django 2.0 on 2019-08-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0008_auto_20190803_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visit_data',
            new_name='visit_date',
        ),
    ]
