# Generated by Django 2.0 on 2019-06-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0009_auto_20190604_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={'verbose_name': '线索', 'verbose_name_plural': '线索管理'},
        ),
    ]
