# Generated by Django 2.0 on 2019-07-10 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0009_auto_20190710_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='ordered_reception',
            field=models.ForeignKey(default=1, help_text='安排接待', on_delete=django.db.models.deletion.CASCADE, related_name='clue_plan_reception', to=settings.AUTH_USER_MODEL, verbose_name='安排接待'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(default='2018-01-01', help_text='安排日期', verbose_name='安排日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_school',
            field=models.ForeignKey(default=1, help_text='安排校区', on_delete=True, related_name='clue_plan_school', to='sys.Department', verbose_name='安排校区'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.TimeField(default='20:00:00', help_text='安排时间', verbose_name='安排时间'),
            preserve_default=False,
        ),
    ]
