# Generated by Django 2.0 on 2019-08-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0009_auto_20190803_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_date',
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.DateTimeField(help_text='安排时间', verbose_name='时间'),
        ),
    ]
