# Generated by Django 2.0 on 2019-06-11 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0010_auto_20190604_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeltype',
            options={'permissions': (('visit_ChannelType', 'Can visit ChannelType'),), 'verbose_name': '渠道类型', 'verbose_name_plural': '渠道类型管理'},
        ),
    ]
