# Generated by Django 2.0 on 2019-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0010_auto_20190803_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='revocatory_reason',
            field=models.CharField(default=1, max_length=200, verbose_name='未到访原因'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.DateTimeField(help_text='安排时间', verbose_name='安排时间'),
        ),
    ]
