# Generated by Django 2.0 on 2019-08-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0011_auto_20190803_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='is_visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.IntegerField(choices=[(0, '约访'), (1, '到访'), (3, '取消')], default=1, verbose_name='访问状态'),
            preserve_default=False,
        ),
    ]
