# Generated by Django 2.0 on 2019-07-10 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0011_auto_20190710_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='cha_name',
            new_name='channel_name',
        ),
        migrations.AlterField(
            model_name='channeltype',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ChannelType_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='channeltype',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ChannelType_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
