# Generated by Django 2.0 on 2019-08-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0012_auto_20190805_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='revocatory_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='未到访原因'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.IntegerField(choices=[(0, '约访'), (1, '到访'), (2, '取消')], verbose_name='访问状态'),
        ),
    ]
