# Generated by Django 2.0 on 2019-06-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0012_auto_20190611_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeltype',
            options={'permissions': (('visit_ChannelType', 'Can visit 渠道类型'),), 'verbose_name': '渠道类型', 'verbose_name_plural': '渠道类型管理'},
        ),
    ]
