# Generated by Django 2.0 on 2019-07-10 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0012_auto_20190710_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channeltype',
            old_name='channel_type_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='channeltype',
            old_name='cha_type_name',
            new_name='name',
        ),
    ]
