# Generated by Django 2.0 on 2019-07-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0013_auto_20190710_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='add',
            new_name='address',
        ),
    ]
