# Generated by Django 2.0 on 2019-08-06 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0013_auto_20190806_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='ordered_reception',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='school',
        ),
    ]
