# Generated by Django 2.0 on 2019-08-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0014_auto_20190806_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.IntegerField(choices=[(0, '约访'), (1, '到访'), (2, '取消')], default=0, verbose_name='访问状态'),
        ),
    ]
