# Generated by Django 2.0 on 2019-07-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0014_auto_20190710_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='clue_id',
            new_name='id',
        ),
    ]
