# Generated by Django 2.0 on 2019-08-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0015_auto_20190806_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.IntegerField(choices=[(0, '约访'), (1, '到访'), (2, '取消'), (3, '改约')], default=0, verbose_name='访问状态'),
        ),
    ]
