# Generated by Django 2.0 on 2019-07-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0015_auto_20190710_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visit_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visit_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visit_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visit_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='visit_type',
            new_name='type',
        ),
    ]
