# Generated by Django 2.0 on 2019-06-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0018_auto_20190611_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeltype',
            options={'permissions': (('view_ChannelType', 'Can view 渠道类型'),), 'verbose_name': '渠道类型', 'verbose_name_plural': '渠道类型管理'},
        ),
    ]
