# Generated by Django 2.0 on 2019-07-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0018_auto_20190711_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='input_time',
            new_name='consult_date',
        ),
    ]
