# Generated by Django 2.0 on 2019-08-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0019_auto_20190809_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={'ordering': ['-create_time'], 'permissions': (('view_clue', 'Can view clue'),), 'verbose_name': '线索', 'verbose_name_plural': '线索管理'},
        ),
        migrations.AlterField(
            model_name='clue',
            name='class_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='报名课时'),
        ),
    ]
