# Generated by Django 2.0 on 2019-07-11 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0019_auto_20190711_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRecord',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('del_flag', models.BooleanField(default=False, help_text='已删除', verbose_name='已删除')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=150, null=True, verbose_name='备注')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=1000)),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clue.Clue', verbose_name='关联线索')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
