# Generated by Django 2.0 on 2019-07-11 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clue', '0020_followrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrecord',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followrecord',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
            preserve_default=False,
        ),
    ]
