# Generated by Django 2.0 on 2019-08-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0020_auto_20190809_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={'ordering': ['-create_time'], 'permissions': (('view_线索', 'Can view clue'),), 'verbose_name': '线索', 'verbose_name_plural': '线索管理'},
        ),
    ]
