# Generated by Django 2.0 on 2019-07-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0021_auto_20190711_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='next_time',
            field=models.DateTimeField(default='2018-01-01', help_text='下次联系时间', verbose_name='下次联系时间'),
            preserve_default=False,
        ),
    ]
