# Generated by Django 2.0 on 2019-08-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0021_auto_20190809_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={'ordering': ['-create_time'], 'verbose_name': '线索', 'verbose_name_plural': '线索管理'},
        ),
    ]
