# Generated by Django 2.0 on 2019-08-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0022_auto_20190810_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={'ordering': ['-create_time'], 'permissions': (('Can view clue', 'view_线索'),), 'verbose_name': '线索', 'verbose_name_plural': '线索管理'},
        ),
    ]
