# Generated by Django 2.0 on 2019-07-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0022_clue_next_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='next_time',
            field=models.DateTimeField(blank=True, help_text='下次联系时间', null=True, verbose_name='下次联系时间'),
        ),
    ]
