# Generated by Django 2.0 on 2019-07-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0023_auto_20190712_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='is_importance',
            field=models.BooleanField(default=1, help_text='是否重要客户', verbose_name='重要客户'),
            preserve_default=False,
        ),
    ]
