# Generated by Django 2.0 on 2019-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0023_auto_20190810_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='failing_type',
        ),
        migrations.AddField(
            model_name='clue',
            name='failing_type',
            field=models.ManyToManyField(blank=True, to='clue.FailingType', verbose_name='未成交原因类型'),
        ),
    ]
