# Generated by Django 2.0 on 2019-07-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0024_clue_is_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '待跟进'), (1, '下次联系'), (2, '成功约访'), (3, '已到访'), (4, '无法成交'), (5, '已报名')], help_text="线索状态((0, '待跟进'), (1, '下次联系'), (2, '成功约访'), (3, '已到访'), (4, '无法成交'), (5, '已报名'))", null=True, verbose_name='线索状态'),
        ),
    ]
