# Generated by Django 2.0 on 2019-08-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduadmin', '0005_auto_20190803_1720'),
        ('clue', '0024_auto_20190810_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='enroll_course',
        ),
        migrations.AddField(
            model_name='clue',
            name='enroll_course',
            field=models.ManyToManyField(blank=True, to='eduadmin.Course', verbose_name='报名课程'),
        ),
        migrations.RemoveField(
            model_name='clue',
            name='failing_type',
        ),
        migrations.AddField(
            model_name='clue',
            name='failing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clue.FailingType', verbose_name='未成交原因类型'),
        ),
    ]
