# Generated by Django 2.0 on 2019-07-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0025_auto_20190712_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='is_importance',
            field=models.NullBooleanField(help_text='是否重要客户', verbose_name='重要客户'),
        ),
    ]
