# Generated by Django 2.0 on 2019-08-12 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0026_auto_20190811_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={'ordering': ['is_importance', '-update_time'], 'verbose_name': '线索', 'verbose_name_plural': '线索管理'},
        ),
    ]
