# Generated by Django 2.0 on 2019-07-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0026_auto_20190717_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='next_data',
            field=models.DateField(blank=True, help_text='下次联系日期', null=True, verbose_name='下次联系日期'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='consult_date',
            field=models.DateField(help_text='录入日期', verbose_name='录入日期'),
        ),
        migrations.AlterField(
            model_name='clue',
            name='next_time',
            field=models.TimeField(blank=True, help_text='下次联系时间', null=True, verbose_name='下次联系时间'),
        ),
    ]
