# Generated by Django 2.0 on 2019-07-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0027_auto_20190717_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clue',
            old_name='next_data',
            new_name='next_date',
        ),
    ]
