# Generated by Django 2.0 on 2019-07-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0028_auto_20190717_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='test_time',
            field=models.DateTimeField(default='2018-02-02 11:11:11'),
            preserve_default=False,
        ),
    ]
