# Generated by Django 2.0 on 2019-08-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0028_auto_20190812_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={'ordering': ['is_importance', '-update_time'], 'permissions': (('view_clue', 'Can view 线索'),), 'verbose_name': '线索', 'verbose_name_plural': '线索管理'},
        ),
    ]
