# Generated by Django 2.0 on 2019-07-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0029_clue_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='test_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
