# Generated by Django 2.0 on 2019-07-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0030_auto_20190718_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='next_date',
        ),
        migrations.RemoveField(
            model_name='clue',
            name='test_time',
        ),
        migrations.AlterField(
            model_name='clue',
            name='next_time',
            field=models.DateTimeField(blank=True, help_text='下次联系时间', null=True, verbose_name='下次联系时间'),
        ),
    ]
