# Generated by Django 2.0 on 2019-07-18 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0031_auto_20190718_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailingType',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('del_flag', models.BooleanField(default=False, help_text='已删除', verbose_name='已删除')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=150, null=True, verbose_name='备注')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=25, verbose_name='无法成交原因类型')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clue',
            name='failing_cause',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='未成交原因'),
        ),
        migrations.AddField(
            model_name='clue',
            name='failing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clue.FailingType', verbose_name='未成交原因类型'),
        ),
    ]
