# Generated by Django 2.0 on 2019-08-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0031_auto_20190812_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='is_over',
            field=models.BooleanField(default=False, verbose_name='线索结束状态'),
        ),
    ]
