# Generated by Django 2.0 on 2019-08-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0032_clue_is_over'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={'ordering': ['is_over', 'is_importance', '-update_time'], 'permissions': (('view_clue', 'Can view 线索'),), 'verbose_name': '线索', 'verbose_name_plural': '线索管理'},
        ),
        migrations.AlterField(
            model_name='clue',
            name='is_importance',
            field=models.BooleanField(default=False, help_text='是否重要客户', verbose_name='重要客户'),
        ),
    ]
