# Generated by Django 2.0 on 2019-07-18 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0032_auto_20190718_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='failing_type',
        ),
    ]
