# Generated by Django 2.0 on 2019-07-18 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0033_remove_clue_failing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='failing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clue.FailingType', verbose_name='未成交原因类型'),
        ),
    ]
