# Generated by Django 2.0 on 2019-07-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0034_clue_failing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrecord',
            name='clue_status',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
    ]
