# Generated by Django 2.0 on 2019-08-14 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0035_auto_20190814_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clue',
            options={'ordering': ['-is_over', '-is_importance', '-update_time'], 'permissions': (('view_clue', 'Can view 线索'),), 'verbose_name': '线索', 'verbose_name_plural': '线索管理'},
        ),
    ]
