# Generated by Django 2.0 on 2019-07-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0036_auto_20190718_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrecord',
            name='datetime',
        ),
        migrations.AddField(
            model_name='followrecord',
            name='follow_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
