# Generated by Django 2.0 on 2019-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0037_auto_20190814_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='enroll_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='报名金额'),
        ),
    ]
