# Generated by Django 2.0 on 2019-07-21 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0037_auto_20190718_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='time',
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='安排时间', verbose_name='时间'),
            preserve_default=False,
        ),
    ]
