# Generated by Django 2.0 on 2019-08-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0040_auto_20190827_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='consult_date',
            field=models.DateField(auto_now_add=True, default='2018-08-08', help_text='录入日期', verbose_name='录入日期'),
            preserve_default=False,
        ),
    ]
