# Generated by Django 2.0 on 2019-07-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_key',
            field=models.CharField(default=1, max_length=25, unique=True, verbose_name='资源key'),
            preserve_default=False,
        ),
    ]
