# Generated by Django 2.0 on 2019-07-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='group',
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default='admin', help_text='角色名称', max_length=10, verbose_name='角色名称'),
            preserve_default=False,
        ),
    ]
