# Generated by Django 2.0 on 2019-07-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0002_resource_resource_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dep_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dep_tel',
            new_name='tel',
        ),
    ]
