# Generated by Django 2.0 on 2019-07-03 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0003_auto_20190703_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('del_flag', models.BooleanField(default=False, help_text='已删除', verbose_name='已删除')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=150, null=True, verbose_name='备注')),
                ('resource_id', models.AutoField(help_text='资源id', primary_key=True, serialize=False, verbose_name='资源编号')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源管理',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='del_flag',
            field=models.BooleanField(default=False, help_text='已删除', verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='role',
            name='remark',
            field=models.CharField(blank=True, help_text='备注', max_length=150, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='role',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='role',
            name='resources',
            field=models.ManyToManyField(help_text='可访问资源', to='sys.Resource', verbose_name='可访问资源'),
        ),
    ]
