# Generated by Django 2.0 on 2019-07-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0004_auto_20190723_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
