# Generated by Django 2.0 on 2019-07-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0004_auto_20190703_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='resources',
            field=models.ManyToManyField(blank=True, help_text='可访问资源', null=True, to='sys.Resource', verbose_name='可访问资源'),
        ),
    ]
