# Generated by Django 2.0 on 2019-07-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0005_auto_20190710_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.IntegerField(default=1, verbose_name='员工电话'),
            preserve_default=False,
        ),
    ]
