# Generated by Django 2.0 on 2019-07-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0006_user_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(help_text='部门id', to='sys.Department', verbose_name='所属部门'),
        ),
    ]
