# Generated by Django 2.0 on 2019-07-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0006_auto_20190703_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(default=1, help_text='资源名称', max_length=15, verbose_name='资源名称'),
            preserve_default=False,
        ),
    ]
