# Generated by Django 2.0 on 2019-07-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0006_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
    ]
