# Generated by Django 2.0 on 2019-07-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0007_resource_resource_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='resources',
            new_name='resource',
        ),
    ]
