# Generated by Django 2.0 on 2019-07-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0007_auto_20190712_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(blank=True, help_text='部门id', null=True, to='sys.Department', verbose_name='所属部门'),
        ),
    ]
