# Generated by Django 2.0 on 2019-07-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0007_remove_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
