# Generated by Django 2.0 on 2019-07-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0008_auto_20190713_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(blank=True, help_text='部门id', to='sys.Department', verbose_name='所属部门'),
        ),
    ]
