# Generated by Django 2.0 on 2019-07-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0009_auto_20190713_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resource',
            field=models.ManyToManyField(blank=True, help_text='拥有资源', to='sys.Resource', verbose_name='拥有资源'),
        ),
    ]
