# Generated by Django 2.0 on 2019-07-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0011_auto_20190713_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=10, verbose_name='员工电话'),
        ),
    ]
