# Generated by Django 2.0 on 2019-07-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0012_auto_20190722_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=12, verbose_name='员工电话'),
        ),
    ]
