# Generated by Django 2.0 on 2019-07-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0012_auto_20190726_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='resource',
        ),
    ]
