# Generated by Django 2.0 on 2019-07-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0012_user_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resource',
        ),
        migrations.AddField(
            model_name='user',
            name='resource',
            field=models.ManyToManyField(help_text='拥有资源', to='sys.Resource', verbose_name='拥有资源'),
        ),
    ]
