# Generated by Django 2.0 on 2019-07-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0013_remove_role_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='role',
            name='resource',
            field=models.ManyToManyField(blank=True, help_text='可访问资源', null=True, to='sys.Resource', verbose_name='可访问资源'),
        ),
    ]
