# Generated by Django 2.0 on 2019-07-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0013_auto_20190704_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='resource',
            field=models.ManyToManyField(help_text='可访问资源', to='sys.Resource', verbose_name='可访问资源'),
        ),
    ]
