# Generated by Django 2.0 on 2019-07-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0014_auto_20190704_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.IntegerField(choices=[(1, '菜单权限'), (2, '按钮权限')], default=1),
            preserve_default=False,
        ),
    ]
