# Generated by Django 2.0 on 2019-07-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0014_auto_20190726_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='roles',
        ),
    ]
