# Generated by Django 2.0 on 2019-07-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0015_auto_20190726_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='resource',
            new_name='resources',
        ),
    ]
