# Generated by Django 2.0 on 2019-07-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0015_auto_20190722_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPermissions',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('del_flag', models.BooleanField(default=False, help_text='已删除', verbose_name='已删除')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=150, null=True, verbose_name='备注')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='数据权限编号')),
                ('name', models.CharField(max_length=25, verbose_name='数据权限名称')),
                ('key', models.CharField(max_length=25, verbose_name='数据权限key')),
            ],
            options={
                'verbose_name': '数据权限',
                'verbose_name_plural': '数据权限管理',
            },
        ),
    ]
