# Generated by Django 2.0 on 2019-07-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0016_auto_20190726_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='角色名称', max_length=10, unique=True, verbose_name='角色名称'),
        ),
    ]
