# Generated by Django 2.0 on 2019-07-23 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0016_datapermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapermissions',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_permissions_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapermissions',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_permissions_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
            preserve_default=False,
        ),
    ]
