# Generated by Django 2.0 on 2019-07-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0017_auto_20190723_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='data_permissions',
            field=models.ManyToManyField(to='sys.DataPermissions', verbose_name='可访问数据'),
        ),
    ]
