# Generated by Django 2.0 on 2019-07-26 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0017_auto_20190726_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='角色名称', max_length=10, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='resource',
            field=models.ManyToManyField(blank=True, help_text='可访问资源', to='sys.Resource', verbose_name='可访问资源'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'creator')},
        ),
    ]
