# Generated by Django 2.0 on 2019-07-23 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0018_role_data_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='data_permissions',
        ),
        migrations.AddField(
            model_name='role',
            name='data_permissions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sys.DataPermissions', verbose_name='可访问数据'),
            preserve_default=False,
        ),
    ]
