# Generated by Django 2.0 on 2019-07-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0018_auto_20190726_1546'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
    ]
