# Generated by Django 2.0 on 2019-07-29 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0019_auto_20190726_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapermissions',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
        ),
    ]
