# Generated by Django 2.0 on 2019-07-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0020_auto_20190729_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(help_text='部门id', to='sys.Department', verbose_name='所属部门'),
        ),
    ]
