# Generated by Django 2.0 on 2019-08-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0021_auto_20190729_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qywxid',
            field=models.CharField(default='1', max_length=20, verbose_name='企业微信userid'),
            preserve_default=False,
        ),
    ]
