# Generated by Django 2.0 on 2019-08-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0023_auto_20190810_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='resource',
            new_name='resources',
        ),
    ]
