# Generated by Django 2.0 on 2019-08-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0024_auto_20190810_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='data_permissions',
            new_name='data_permission',
        ),
    ]
