# Generated by Django 2.0 on 2019-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0025_auto_20190810_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='data_permission',
            field=models.IntegerField(choices=[(0, '个人数据'), (10, '部门数据'), (20, '本部门及下级部门数据'), (30, '公司数据')], verbose_name='可访问数据'),
        ),
    ]
