# Generated by Django 2.0 on 2019-08-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0026_auto_20190810_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='角色名称', max_length=50, verbose_name='角色名称'),
        ),
    ]
