# Generated by Django 2.0 on 2019-08-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0027_auto_20190811_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qywxid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='企业微信userid'),
        ),
    ]
