# Generated by Django 2.0 on 2019-05-31 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSchool',
            fields=[
                ('sch_id', models.AutoField(help_text='校区id', primary_key=True, serialize=False, verbose_name='校区编号')),
                ('sch_name', models.CharField(help_text='校区名称', max_length=20, verbose_name='校区名称')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='课程类型', max_length=15, verbose_name='课程类型')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edu_admin.CourseType'),
        ),
    ]
