# Generated by Django 2.0 on 2019-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSchool',
            fields=[
                ('sch_id', models.AutoField(help_text='校区id', primary_key=True, serialize=False, verbose_name='校区编号')),
                ('sch_name', models.CharField(help_text='校区名称', max_length=20, verbose_name='校区名称')),
            ],
            options={
                'verbose_name': '校区',
                'verbose_name_plural': '校区管理',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cou_id', models.AutoField(primary_key=True, serialize=False)),
                ('cou_type', models.IntegerField(choices=[(0, '一对一'), (1, '班课')])),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('cou_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='课程类型', max_length=15, verbose_name='课程类型')),
            ],
            options={
                'verbose_name': '课程类型',
                'verbose_name_plural': '课程类型',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.AutoField(help_text='科系id', primary_key=True, serialize=False, verbose_name='科系编号')),
                ('sub_name', models.CharField(help_text='科系名称', max_length=10, verbose_name='科系名称')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tea_id', models.AutoField(help_text='教师id', primary_key=True, serialize=False, verbose_name='教师编号')),
                ('tea_name', models.CharField(help_text='教师姓名', max_length=6, verbose_name='教师姓名')),
            ],
        ),
    ]
