# Generated by Django 2.0 on 2019-06-03 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edu_admin', '0001_initial'),
        ('sys_set', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user_id',
            field=models.ForeignKey(blank=True, help_text='员工id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='员工编号'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edu_admin.CourseType'),
        ),
        migrations.AddField(
            model_name='branchschool',
            name='org_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sys_set.Organization'),
        ),
    ]
