# Generated by Django 2.0 on 2019-05-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchschool',
            options={'verbose_name': '校区', 'verbose_name_plural': '小区管理'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='coursetype',
            options={'verbose_name': '课程类型', 'verbose_name_plural': '课程类型'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='cou_id',
        ),
        migrations.RenameField(
            model_name='coursetype',
            old_name='id',
            new_name='cou_type_id',
        ),
    ]
