# Generated by Django 2.0.5 on 2019-06-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0003_auto_20190603_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.AddField(
            model_name='course',
            name='course_subjects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='edu_admin.Subjects', verbose_name='科系'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='cou_type',
            field=models.IntegerField(choices=[(0, '一对一'), (1, '班课')], verbose_name='课程类型'),
        ),
        migrations.DeleteModel(
            name='CourseType',
        ),
    ]
