# Generated by Django 2.0.5 on 2019-06-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0004_auto_20190603_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='小提琴', help_text='课程名称', max_length=15, verbose_name='课程名称'),
            preserve_default=False,
        ),
    ]
