# Generated by Django 2.0 on 2019-06-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0005_course_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': '科系', 'verbose_name_plural': '科系管理'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='cou_name',
        ),
    ]
