# Generated by Django 2.0 on 2019-06-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0006_auto_20190604_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师管理'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='tea_name',
        ),
    ]
