# Generated by Django 2.0 on 2019-06-11 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0007_auto_20190604_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程管理'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_id',
            field=models.ForeignKey(blank=True, help_text='员工id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='教师姓名'),
        ),
    ]
