# Generated by Django 2.0 on 2019-07-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cou_id', models.AutoField(primary_key=True, serialize=False)),
                ('cou_type', models.IntegerField(choices=[(0, '一对一'), (1, '班课')], verbose_name='课程类型')),
                ('cou_name', models.CharField(help_text='课程名称', max_length=15, verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程管理',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('sub_id', models.AutoField(help_text='科系id', primary_key=True, serialize=False, verbose_name='科系编号')),
                ('sub_name', models.CharField(help_text='科系名称', max_length=10, verbose_name='科系名称')),
            ],
            options={
                'verbose_name': '科系',
                'verbose_name_plural': '科系管理',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tea_id', models.AutoField(help_text='教师id', primary_key=True, serialize=False, verbose_name='教师编号')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师管理',
            },
        ),
    ]
