# Generated by Django 2.0 on 2019-07-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0021_auto_20190729_1632'),
        ('clue', '0007_auto_20190730_1700'),
        ('eduadmin', '0002_auto_20190723_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('del_flag', models.BooleanField(default=False, help_text='已删除', verbose_name='已删除')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=150, null=True, verbose_name='备注')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='学员编号')),
                ('name', models.CharField(max_length=7, verbose_name='学员姓名')),
                ('tel', models.CharField(max_length=12, verbose_name='联系电话')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='学员生日')),
                ('sex', models.IntegerField(blank=True, choices=[(0, '女'), (1, '男')], help_text="((0, '女'), (1, '男'))", null=True, verbose_name='性别')),
                ('father_name', models.CharField(blank=True, max_length=5, null=True, verbose_name='父亲姓名')),
                ('father_tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='父亲电话')),
                ('mother_name', models.CharField(blank=True, max_length=5, null=True, verbose_name='母亲姓名')),
                ('mother_tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='母亲电话')),
                ('status', models.IntegerField(choices=[(0, '新签'), (1, '已缴费'), (2, '上课中'), (3, '停课'), (4, '结课')], verbose_name='学员状态')),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clue.Clue', verbose_name='关联线索')),
                ('organization', models.ForeignKey(help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys.Department', verbose_name='归属校区')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
