# Generated by Django 2.0 on 2019-07-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduadmin', '0002_auto_20190705_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cou_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cou_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='cou_type',
            new_name='type',
        ),
    ]
