# Generated by Django 2.0 on 2019-07-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduadmin', '0003_auto_20190710_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.IntegerField(choices=[(0, '一对一'), (1, '班课')], help_text="((0, '一对一'), (1, '班课'))", verbose_name='课程类型'),
        ),
    ]
