# Generated by Django 2.0 on 2019-07-30 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sys', '0021_auto_20190729_1632'),
        ('eduadmin', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='del_flag',
            field=models.BooleanField(default=False, help_text='已删除', verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='remark',
            field=models.CharField(blank=True, help_text='备注', max_length=150, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='course',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='del_flag',
            field=models.BooleanField(default=False, help_text='已删除', verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='remark',
            field=models.CharField(blank=True, help_text='备注', max_length=150, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='del_flag',
            field=models.BooleanField(default=False, help_text='已删除', verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='organization',
            field=models.ForeignKey(default=1, help_text='公司id', on_delete=django.db.models.deletion.CASCADE, to='sys.Organization', verbose_name='归属公司'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='remark',
            field=models.CharField(blank=True, help_text='备注', max_length=150, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
