# Generated by Django 2.0 on 2019-07-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduadmin', '0004_auto_20190711_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='tea_id',
            new_name='id',
        ),
    ]
