# Generated by Django 2.0 on 2019-08-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduadmin', '0004_auto_20190730_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, '新签'), (1, '已缴费'), (2, '上课中'), (3, '停课'), (4, '结课')], default=0, verbose_name='学员状态'),
        ),
    ]
