# Generated by Django 2.0 on 2019-07-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduadmin', '0005_auto_20190711_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
