# Generated by Django 2.0 on 2019-07-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduadmin', '0009_auto_20190720_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(to='eduadmin.Course', verbose_name='所授课程'),
        ),
    ]
