# Generated by Django 2.0 on 2019-07-21 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduadmin', '0010_teacher_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='sub_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='sub_name',
            new_name='name',
        ),
    ]
