# Generated by Django 2.0 on 2019-05-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(help_text='组织id', primary_key=True, serialize=False, verbose_name='组织编号')),
                ('org_name', models.CharField(help_text='公司名称', max_length=20, verbose_name='公司名称')),
                ('org_add', models.CharField(blank=True, help_text='公司地址', max_length=50, null=True, verbose_name='公司地址')),
                ('contacts_man', models.CharField(help_text='公司联系人', max_length=6, verbose_name='公司联系人')),
                ('contacts_tel', models.CharField(help_text='联系人电话', max_length=30, verbose_name='联系人电话')),
                ('legal_person', models.CharField(blank=True, help_text='公司法人', max_length=6, null=True, verbose_name='公司法人')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
            },
        ),
    ]
