# Generated by Django 2.0.5 on 2019-06-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_set', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '公司', 'verbose_name_plural': '公司管理'},
        ),
    ]
