# Generated by Django 2.0.5 on 2019-06-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_set', '0002_auto_20190601_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dep_id', models.AutoField(help_text='部门id', primary_key=True, serialize=False, verbose_name='部门编号')),
                ('dep_type', models.IntegerField(choices=[(0, '分公司'), (1, '校区'), (2, '部门')], null=True, verbose_name='类型')),
                ('dep_name', models.CharField(help_text='部门名称', max_length=10, verbose_name='部门名称')),
                ('dep_tel', models.CharField(help_text='电话', max_length=15, null=True, verbose_name='电话')),
                ('org_id', models.ForeignKey(help_text='公司id', on_delete=django.db.models.deletion.DO_NOTHING, to='sys_set.Organization', verbose_name='公司名称')),
                ('superior_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sys_set.Department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门管理',
            },
        ),
    ]
