# Generated by Django 2.0 on 2019-06-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_set', '0002_auto_20190603_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='creator',
        ),
    ]
