# Generated by Django 2.0 on 2019-06-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_set', '0003_auto_20190603_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dep_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='org_id',
        ),
    ]
