# Generated by Django 2.0 on 2019-06-04 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_set', '0005_auto_20190603_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='department',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_operator', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
