# Generated by Django 2.0 on 2019-06-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_set', '0006_auto_20190604_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='head_pic',
            field=models.URLField(blank=True, help_text='用户头像url', null=True, verbose_name='头像'),
        ),
    ]
