# Generated by Django 2.0 on 2019-06-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_set', '0008_auto_20190628_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/%Y/%m/%d', verbose_name='图片url'),
        ),
    ]
