# Generated by Django 2.0 on 2019-06-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_set', '0010_auto_20190630_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dep_id',
            field=models.ForeignKey(default=1, help_text='部门id', on_delete=django.db.models.deletion.DO_NOTHING, to='sys_set.Department', verbose_name='所属部门'),
            preserve_default=False,
        ),
    ]
