# Generated by Django 2.0 on 2019-06-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_set', '0011_userprofile_dep_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dep_id',
            new_name='dep',
        ),
    ]
