# Generated by Django 2.0 on 2019-07-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='TOKEN_id')),
                ('token', models.CharField(max_length=1000, verbose_name='token值')),
                ('is_active', models.BooleanField(verbose_name='活跃用户')),
            ],
        ),
    ]
