# Generated by Django 2.0 on 2019-07-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_token_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token_id',
            new_name='id',
        ),
    ]
